

"""
Results export for presentation

"""


import xlsxwriter as xw
import numpy as np

workbook = xw.Workbook('results_output.xlsx')
format_header = workbook.add_format({'bold': 1, 'align': 'centre', 'bg_color': 'red', 'font_color': 'white'})
format_rowlabel = workbook.add_format({'bold': 1, 'align': 'centre', 'font_color': 'red'})
format_obs = workbook.add_format({'align': 'centre'})

# sheet1 SAR压力测试
worksheet1 = workbook.add_worksheet('压力测试结果')
worksheet1.set_column('A:A', 30)
worksheet1.set_column('B:B', 30)

worksheet1.write('A1', "名称", format_header)
worksheet1.write('B1', "取值", format_header)
worksheet1.write(1, 0, "实际资本损失", format_rowlabel)
worksheet1.write(1, 1, ACLOSS, format_obs)
worksheet1.write(2, 0, "压力下最低资本", format_rowlabel)
worksheet1.write(2, 1, MCStressed, format_obs)
worksheet1.write(3, 0, "压力下偿付能力", format_rowlabel)
worksheet1.write(3, 1, SAR_Stressed, format_obs)

# sheet2 迭代
worksheet2 = workbook.add_worksheet('风险总量计算')
worksheet2.set_column('A:A', 30)
worksheet2.set_column('B:B', 30)

worksheet2.write('A1', "名称", format_header)
worksheet2.write('B1', "取值", format_header)
worksheet2.write(1, 0, "迭代前溢额", format_rowlabel)
worksheet2.write(1, 1, RiskSur_total_preiter, format_obs)
worksheet2.write(2, 0, "迭代后溢额", format_rowlabel)
worksheet2.write(2, 1, RiskSur_total_aftiter, format_obs)
worksheet2.write(3, 0, "迭代次数", format_rowlabel)
worksheet2.write(3, 1, itercount, format_obs)
worksheet2.write(4, 0, "迭代后风险溢额与最低资本比例", format_rowlabel)
worksheet2.write(4, 1, Surpluspercentage, format_obs)

# sheet3 溢额分解
worksheet3 = workbook.add_worksheet('风险溢额分解')
worksheet3.set_column('A:A', 30)
worksheet3.set_column('B:B', 30)
worksheet3.set_column('C:C', 30)
worksheet3.set_column('D:D', 30)
worksheet3.set_column('E:E', 30)
worksheet3.set_column('F:F', 30)
worksheet3.set_column('G:G', 30)
worksheet3.set_column('H:H', 30)
worksheet3.set_column('I:I', 30)

worksheet3.write('A1', "维度", format_header)
worksheet3.write('B1', "分配值", format_header)
worksheet3.write('C1', "风险基准值", format_header)
worksheet3.write('D1', "基准调整值", format_header)
worksheet3.write('E1', "策略分配比例", format_header)
worksheet3.write('F1', "策略分配值", format_header)
worksheet3.write('G1', "最终值", format_header)
worksheet3.write('H1', "分配值占总溢额比例", format_header)
worksheet3.write('I1', "最终值占总溢额比例", format_header)

worksheet3.write(1,0,"保险风险-损失发生",format_rowlabel)
worksheet3.write(1,1,RiskSur_ins_los_decompose,format_obs)
worksheet3.write(1,2,RiskSur_bench_loss_RisDiv,format_obs)
worksheet3.write(1,3,RiskSur_benchadjusted_loss_RisDiv,format_obs)
worksheet3.write(1,4,ins_los_perc,format_obs)
worksheet3.write(1,5,RiskSur_ins_los_tacadjust,format_obs)
worksheet3.write(1,6,RiskSur_ins_loss_final_RisDiv,format_obs)
worksheet3.write(1,7,RiskSur_ins_los_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(1,8,RiskSur_ins_loss_final_RisDiv * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(2,0,"保险风险-费用",format_rowlabel)
worksheet3.write(2,1,RiskSur_ins_exp_decompose,format_obs)
worksheet3.write(2,2,RiskSur_ins_exp_bench,format_obs)
worksheet3.write(2,3,RiskSur_ins_exp_benchadjusted,format_obs)
worksheet3.write(2,4,ins_exp_perc,format_obs)
worksheet3.write(2,5,RiskSur_ins_exp_tacadjust,format_obs)
worksheet3.write(2,6,RiskSur_ins_exp_final,format_obs)
worksheet3.write(2,7,RiskSur_ins_exp_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(2,8,RiskSur_ins_exp_final * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(3,0,"保险风险-退保",format_rowlabel)
worksheet3.write(3,1,RiskSur_ins_lap_decompose,format_obs)
worksheet3.write(3,2,RiskSur_ins_lap_bench,format_obs)
worksheet3.write(3,3,RiskSur_ins_lap_benchadjusted,format_obs)
worksheet3.write(3,4,ins_lap_perc,format_obs)
worksheet3.write(3,5,RiskSur_ins_lap_tacadjust,format_obs)
worksheet3.write(3,6,RiskSur_ins_lap_final,format_obs)
worksheet3.write(3,7,RiskSur_ins_lap_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(3,8,RiskSur_ins_lap_final * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(4,0,"保险风险-非寿险风险",format_rowlabel)
worksheet3.write(4,1,RiskSur_pc_decompose,format_obs)
worksheet3.write(4,2,RiskSur_pc_bench,format_obs)
worksheet3.write(4,3,RiskSur_pc_benchadjusted,format_obs)
worksheet3.write(4,4,pc_perc,format_obs)
worksheet3.write(4,5,RiskSur_pc_tacadjust,format_obs)
worksheet3.write(4,6,RiskSur_pc_final,format_obs)
worksheet3.write(4,7,RiskSur_pc_decompose * (Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(4,8,RiskSur_pc_final * (Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(5,0,"市场风险-利率",format_rowlabel)
worksheet3.write(5,1,RiskSur_mar_int_decompose,format_obs)
worksheet3.write(5,2,RiskSur_mar_int_bench,format_obs)
worksheet3.write(5,3,RiskSur_mar_int_benchadjusted,format_obs)
worksheet3.write(5,4,mar_int_perc,format_obs)
worksheet3.write(5,5,RiskSur_mar_int_tacadjust,format_obs)
worksheet3.write(5,6,RiskSur_mar_int_final,format_obs)
worksheet3.write(5,7,RiskSur_mar_int_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(5,8,RiskSur_mar_int_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(6,0,"市场风险-上市权益",format_rowlabel)
worksheet3.write(6,1,RiskSur_mar_equ_listed_decompose,format_obs)
worksheet3.write(6,2,RiskSur_mar_equ_listed_bench,format_obs)
worksheet3.write(6,3,RiskSur_mar_equ_listed_benchadjusted,format_obs)
worksheet3.write(6,4,mar_equ_listed_perc,format_obs)
worksheet3.write(6,5,RiskSur_mar_equ_listed_tacadjust,format_obs)
worksheet3.write(6,6,RiskSur_mar_equ_listed_final,format_obs)
worksheet3.write(6,7,RiskSur_mar_equ_listed_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(6,8,RiskSur_mar_equ_listed_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(7,0,"市场风险-另类权益-总计",format_rowlabel)
worksheet3.write(7,1,RiskSur_mar_equ_alter_decompose,format_obs)
worksheet3.write(7,2,RiskSur_mar_equ_alter_bench,format_obs)
worksheet3.write(7,3,RiskSur_mar_equ_alter_benchadjusted,format_obs)
worksheet3.write(7,4,mar_equ_alter_est_perc+mar_equ_alter_energy_perc+mar_equ_alter_oth_perc,format_obs)
worksheet3.write(7,5,RiskSur_mar_equ_alter_tacadjust,format_obs)
worksheet3.write(7,6,RiskSur_mar_equ_alter_final,format_obs)
worksheet3.write(7,7,RiskSur_mar_equ_alter_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(7,8,RiskSur_mar_equ_alter_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(8,0,"市场风险-另类权益-房地产",format_rowlabel)
worksheet3.write(8,1,RiskSur_mar_equ_alter_est_decompose,format_obs)
worksheet3.write(8,2,RiskSur_mar_equ_alter_est_bench,format_obs)
worksheet3.write(8,3,RiskSur_mar_equ_alter_est_benchadjusted,format_obs)
worksheet3.write(8,4,mar_equ_alter_est_perc,format_obs)
worksheet3.write(8,5,RiskSur_mar_equ_alter_est_tacadjust,format_obs)
worksheet3.write(8,6,RiskSur_mar_equ_alter_est_final,format_obs)
worksheet3.write(8,7,RiskSur_mar_equ_alter_est_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(8,8,RiskSur_mar_equ_alter_est_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(9,0,"市场风险-另类权益-能源",format_rowlabel)
worksheet3.write(9,1,RiskSur_mar_equ_alter_energy_decompose,format_obs)
worksheet3.write(9,2,RiskSur_mar_equ_alter_energy_bench,format_obs)
worksheet3.write(9,3,RiskSur_mar_equ_alter_energy_benchadjusted,format_obs)
worksheet3.write(9,4,mar_equ_alter_energy_perc,format_obs)
worksheet3.write(9,5,RiskSur_mar_equ_alter_energy_tacadjust,format_obs)
worksheet3.write(9,6,RiskSur_mar_equ_alter_energy_final,format_obs)
worksheet3.write(9,7,RiskSur_mar_equ_alter_energy_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(9,8,RiskSur_mar_equ_alter_energy_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(10,0,"市场风险-另类权益-金融",format_rowlabel)
worksheet3.write(10,1,RiskSur_mar_equ_alter_finance_decompose,format_obs)
worksheet3.write(10,2,RiskSur_mar_equ_alter_finance_bench,format_obs)
worksheet3.write(10,3,RiskSur_mar_equ_alter_finance_benchadjusted,format_obs)
worksheet3.write(10,4,mar_equ_alter_finance_perc,format_obs)
worksheet3.write(10,5,RiskSur_mar_equ_alter_finance_tacadjust,format_obs)
worksheet3.write(10,6,RiskSur_mar_equ_alter_finance_final,format_obs)
worksheet3.write(10,7,RiskSur_mar_equ_alter_finance_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(10,8,RiskSur_mar_equ_alter_finance_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(11,0,"市场风险-另类权益-其他行业",format_rowlabel)
worksheet3.write(11,1,RiskSur_mar_equ_alter_oth_decompose,format_obs)
worksheet3.write(11,2,RiskSur_mar_equ_alter_oth_bench,format_obs)
worksheet3.write(11,3,RiskSur_mar_equ_alter_oth_benchadjusted,format_obs)
worksheet3.write(11,4,mar_equ_alter_oth_perc,format_obs)
worksheet3.write(11,5,RiskSur_mar_equ_alter_oth_tacadjust,format_obs)
worksheet3.write(11,6,RiskSur_mar_equ_alter_oth_final,format_obs)
worksheet3.write(11,7,RiskSur_mar_equ_alter_oth_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(11,8,RiskSur_mar_equ_alter_oth_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(12,0,"市场风险-房地产",format_rowlabel)
worksheet3.write(12,1,RiskSur_mar_est_decompose,format_obs)
worksheet3.write(12,2,RiskSur_mar_est_bench,format_obs)
worksheet3.write(12,3,RiskSur_mar_est_benchadjusted,format_obs)
worksheet3.write(12,4,mar_est_perc,format_obs)
worksheet3.write(12,5,RiskSur_mar_est_tacadjust,format_obs)
worksheet3.write(12,6,RiskSur_mar_est_final,format_obs)
worksheet3.write(12,7,RiskSur_mar_est_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(12,8,RiskSur_mar_est_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(13,0,"市场风险-境外固收",format_rowlabel)
worksheet3.write(13,1,RiskSur_mar_ovsefixin_decompose,format_obs)
worksheet3.write(13,2,RiskSur_mar_ovsefixin_bench,format_obs)
worksheet3.write(13,3,RiskSur_mar_ovsefixin_benchadjusted,format_obs)
worksheet3.write(13,4,mar_ovsefixin_perc,format_obs)
worksheet3.write(13,5,RiskSur_mar_ovsefixin_tacadjust,format_obs)
worksheet3.write(13,6,RiskSur_mar_ovsefixin_final,format_obs)
worksheet3.write(13,7,RiskSur_mar_ovsefixin_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(13,8,RiskSur_mar_ovsefixin_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(14,0,"市场风险-境外权益",format_rowlabel)
worksheet3.write(14,1,RiskSur_mar_ovseequ_decompose,format_obs)
worksheet3.write(14,2,RiskSur_mar_ovseequ_bench,format_obs)
worksheet3.write(14,3,RiskSur_mar_ovseequ_benchadjusted,format_obs)
worksheet3.write(14,4,mar_ovseequ_perc,format_obs)
worksheet3.write(14,5,RiskSur_mar_ovseequ_tacadjust,format_obs)
worksheet3.write(14,6,RiskSur_mar_ovseequ_final,format_obs)
worksheet3.write(14,7,RiskSur_mar_ovseequ_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(14,8,RiskSur_mar_ovseequ_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(15,0,"市场风险-汇率",format_rowlabel)
worksheet3.write(15,1,RiskSur_mar_exch_decompose,format_obs)
worksheet3.write(15,2,RiskSur_mar_exch_bench,format_obs)
worksheet3.write(15,3,RiskSur_mar_exch_benchadjusted,format_obs)
worksheet3.write(15,4,mar_exch_perc,format_obs)
worksheet3.write(15,5,RiskSur_mar_exch_tacadjust,format_obs)
worksheet3.write(15,6,RiskSur_mar_exch_final,format_obs)
worksheet3.write(15,7,RiskSur_mar_exch_decompose * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(15,8,RiskSur_mar_exch_final * (Ratio_RisDiv_mar*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(16,0,"信用风险-利差",format_rowlabel)
worksheet3.write(16,1,RiskSur_cr_cs_decompose,format_obs)
worksheet3.write(16,2,RiskSur_cr_cs_bench,format_obs)
worksheet3.write(16,3,RiskSur_cr_cs_benchadjusted,format_obs)
worksheet3.write(16,4,cr_cs_perc,format_obs)
worksheet3.write(16,5,RiskSur_cr_cs_tacadjust,format_obs)
worksheet3.write(16,6,RiskSur_cr_cs_final,format_obs)
worksheet3.write(16,7,RiskSur_cr_cs_decompose * (Ratio_RisDiv_cr*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(16,8,RiskSur_cr_cs_final * (Ratio_RisDiv_cr*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(17,0,"信用风险-违约-公司",format_rowlabel)
worksheet3.write(17,1,RiskSur_cr_def_htmcorpbonds_decompose,format_obs)
worksheet3.write(17,2,RiskSur_cr_def_htmcorpbonds_bench,format_obs)
worksheet3.write(17,3,RiskSur_cr_def_htmcorpbonds_benchadjusted,format_obs)
worksheet3.write(17,4,cr_def_htmcorpbonds_perc,format_obs)
worksheet3.write(17,5,RiskSur_cr_def_htmcorpbonds_tacadjust,format_obs)
worksheet3.write(17,6,RiskSur_cr_def_htmcorpbonds_final,format_obs)
worksheet3.write(17,7,RiskSur_cr_def_htmcorpbonds_decompose * (Ratio_RisDiv_cr*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(17,8,RiskSur_cr_def_htmcorpbonds_final * (Ratio_RisDiv_cr*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

worksheet3.write(18,0,"信用风险-违约-另类固收",format_rowlabel)
worksheet3.write(18,1,RiskSur_cr_def_htmalter_decompose,format_obs)
worksheet3.write(18,2,RiskSur_cr_def_htmalter_bench,format_obs)
worksheet3.write(18,3,RiskSur_cr_def_htmalter_benchadjusted,format_obs)
worksheet3.write(18,4,cr_def_htmalter_perc,format_obs)
worksheet3.write(18,5,RiskSur_cr_def_htmalter_tacadjust,format_obs)
worksheet3.write(18,6,RiskSur_cr_def_htmalter_final,format_obs)
worksheet3.write(18,7,RiskSur_cr_def_htmalter_decompose * (Ratio_RisDiv_cr*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)
worksheet3.write(18,8,RiskSur_cr_def_htmalter_final * (Ratio_RisDiv_cr*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer,format_obs)

# 损失发生率风险
worksheet3.write(20,0, "死亡", format_rowlabel)
worksheet3.write(20,1, RiskSur_ins_los_dea_decompose, format_obs)
worksheet3.write(20,2, RiskSur_ins_los_dea_bench, format_obs)
worksheet3.write(20,3, RiskSur_ins_los_dea_benchadjusted, format_obs)
worksheet3.write(20,4, LossAllocatePercentage[0], format_obs)
worksheet3.write(20,5, RiskSur_ins_los_dea_tacadjust, format_obs)
worksheet3.write(20,6, RiskSur_ins_los_dea_final, format_obs)
worksheet3.write(20,7, RiskSur_ins_los_dea_decompose * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(20,8, RiskSur_ins_los_dea_final * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(21,0, "死亡巨灾", format_rowlabel)
worksheet3.write(21,1, RiskSur_ins_los_catdea_decompose, format_obs)
worksheet3.write(21,2, RiskSur_ins_los_catdea_bench, format_obs)
worksheet3.write(21,3, RiskSur_ins_los_catdea_benchadjusted, format_obs)
worksheet3.write(21,4, 0, format_obs)
worksheet3.write(21,5, 0, format_obs)
worksheet3.write(21,6, RiskSur_ins_los_catdea_final, format_obs)
worksheet3.write(21,7, RiskSur_ins_los_catdea_decompose * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(21,8, RiskSur_ins_los_catdea_final * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(22,0, "长寿风险", format_rowlabel)
worksheet3.write(22,1, RiskSur_ins_los_lonliv_decompose, format_obs)
worksheet3.write(22,2, RiskSur_ins_los_lonliv_bench, format_obs)
worksheet3.write(22,3, RiskSur_ins_los_lonliv_benchadjusted, format_obs)
worksheet3.write(22,4, LossAllocatePercentage[1], format_obs)
worksheet3.write(22,5, RiskSur_ins_los_lonliv_tacadjust, format_obs)
worksheet3.write(22,6, RiskSur_ins_los_lonliv_final, format_obs)
worksheet3.write(22,7, RiskSur_ins_los_lonliv_decompose * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(22,8, RiskSur_ins_los_lonliv_final * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(23,0, "重疾风险", format_rowlabel)
worksheet3.write(23,1, RiskSur_ins_los_des_decompose, format_obs)
worksheet3.write(23,2, RiskSur_ins_los_des_bench, format_obs)
worksheet3.write(23,3, RiskSur_ins_los_des_benchadjusted, format_obs)
worksheet3.write(23,4, LossAllocatePercentage[2], format_obs)
worksheet3.write(23,5, RiskSur_ins_los_des_tacadjust, format_obs)
worksheet3.write(23,6, RiskSur_ins_los_des_final, format_obs)
worksheet3.write(23,7, RiskSur_ins_los_des_decompose * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(23,8, RiskSur_ins_los_des_final * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(24,0, "医疗与健康赔付", format_rowlabel)
worksheet3.write(24,1, RiskSur_ins_los_med_decompose, format_obs)
worksheet3.write(24,2, RiskSur_ins_los_med_bench, format_obs)
worksheet3.write(24,3, RiskSur_ins_los_med_benchadjusted, format_obs)
worksheet3.write(24,4, LossAllocatePercentage[3], format_obs)
worksheet3.write(24,5, RiskSur_ins_los_med_tacadjust, format_obs)
worksheet3.write(24,6, RiskSur_ins_los_med_final, format_obs)
worksheet3.write(24,7, RiskSur_ins_los_med_decompose * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(24,8, RiskSur_ins_los_med_final * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(25,0, "损失发生率-其他", format_rowlabel)
worksheet3.write(25,1, RiskSur_ins_los_oth_decompose, format_obs)
worksheet3.write(25,2, RiskSur_ins_los_oth_bench, format_obs)
worksheet3.write(25,3, RiskSur_ins_los_oth_benchadjusted, format_obs)
worksheet3.write(25,4, 0, format_obs)
worksheet3.write(25,5, 0, format_obs)
worksheet3.write(25,6, RiskSur_ins_los_oth_final, format_obs)
worksheet3.write(25,7, RiskSur_ins_los_oth_decompose * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(25,8, RiskSur_ins_los_oth_final * (Ratio_RisDiv_ins_los*Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

# 退保率风险
worksheet3.write(27,0, "退保风险-个险期交", format_rowlabel)
worksheet3.write(27,1, RiskSur_ins_lap_indi_decompose, format_obs)
worksheet3.write(27,2, RiskSur_ins_lap_indi_bench, format_obs)
worksheet3.write(27,3, RiskSur_ins_lap_indi_benchadjusted, format_obs)
worksheet3.write(27,4, LapAllocatePercentage[0], format_obs)
worksheet3.write(27,5, RiskSur_ins_lap_indi_tacadjust, format_obs)
worksheet3.write(27,6, RiskSur_ins_lap_indi_final, format_obs)
worksheet3.write(27,7, RiskSur_ins_lap_indi_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(27,8, RiskSur_ins_lap_indi_final * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(28,0, "退保风险-银保期交", format_rowlabel)
worksheet3.write(28,1, RiskSur_ins_lap_bank_decompose, format_obs)
worksheet3.write(28,2, RiskSur_ins_lap_bank_bench, format_obs)
worksheet3.write(28,3, RiskSur_ins_lap_bank_benchadjusted, format_obs)
worksheet3.write(28,4, LapAllocatePercentage[1], format_obs)
worksheet3.write(28,5, RiskSur_ins_lap_bank_tacadjust, format_obs)
worksheet3.write(28,6, RiskSur_ins_lap_bank_final, format_obs)
worksheet3.write(28,7, RiskSur_ins_lap_bank_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(28,8, RiskSur_ins_lap_bank_final * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(29,0, "退保风险-经代期交", format_rowlabel)
worksheet3.write(29,1, RiskSur_ins_lap_agent_decompose, format_obs)
worksheet3.write(29,2, RiskSur_ins_lap_agent_bench, format_obs)
worksheet3.write(29,3, RiskSur_ins_lap_agent_benchadjusted, format_obs)
worksheet3.write(29,4, LapAllocatePercentage[2], format_obs)
worksheet3.write(29,5, RiskSur_ins_lap_agent_tacadjust, format_obs)
worksheet3.write(29,6, RiskSur_ins_lap_agent_final, format_obs)
worksheet3.write(29,7, RiskSur_ins_lap_agent_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(29,8, RiskSur_ins_lap_agent_final * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

# 费用风险
worksheet3.write(31,0, "费用风险-个险与经代", format_rowlabel)
worksheet3.write(31,1, RiskSur_ins_exp_indi_agent_decompose, format_obs)
worksheet3.write(31,2, RiskSur_ins_exp_varexp_indi_agent_bench, format_obs)
worksheet3.write(31,3, RiskSur_ins_exp_varexp_indi_agent_benchadjusted, format_obs)
worksheet3.write(31,4, ExpenseAllocatePercentage[0], format_obs)
worksheet3.write(31,5, RiskSur_ins_exp_varexp_indi_agent_tacadjust, format_obs)
worksheet3.write(31,6, RiskSur_ins_exp_varexp_indi_agent_final, format_obs)
worksheet3.write(31,7, RiskSur_ins_exp_indi_agent_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(31,8, RiskSur_ins_exp_varexp_indi_agent_final * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(32,0, "费用风险-银保", format_rowlabel)
worksheet3.write(32,1, RiskSur_ins_exp_bank_decompose, format_obs)
worksheet3.write(32,2, RiskSur_ins_exp_varexp_bank_bench, format_obs)
worksheet3.write(32,3, RiskSur_ins_exp_varexp_bank_benchadjusted, format_obs)
worksheet3.write(32,4, ExpenseAllocatePercentage[1], format_obs)
worksheet3.write(32,5, RiskSur_ins_exp_varexp_bank_tacadjust, format_obs)
worksheet3.write(32,6, RiskSur_ins_exp_varexp_bank_final, format_obs)
worksheet3.write(32,7, RiskSur_ins_exp_bank_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(32,8, RiskSur_ins_exp_varexp_bank_final * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(33,0, "费用风险-网销", format_rowlabel)
worksheet3.write(33,1, RiskSur_ins_exp_web_decompose, format_obs)
worksheet3.write(33,2, RiskSur_ins_exp_varexp_web_bench, format_obs)
worksheet3.write(33,3, RiskSur_ins_exp_varexp_web_benchadjusted, format_obs)
worksheet3.write(33,4, ExpenseAllocatePercentage[2], format_obs)
worksheet3.write(33,5, RiskSur_ins_exp_varexp_web_tacadjust, format_obs)
worksheet3.write(33,6, RiskSur_ins_exp_varexp_web_final, format_obs)
worksheet3.write(33,7, RiskSur_ins_exp_web_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(33,8, RiskSur_ins_exp_varexp_web_final * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(34,0, "费用风险-电销", format_rowlabel)
worksheet3.write(34,1, RiskSur_ins_exp_tel_decompose, format_obs)
worksheet3.write(34,2, RiskSur_ins_exp_varexp_tel_bench, format_obs)
worksheet3.write(34,3, RiskSur_ins_exp_varexp_tel_benchadjusted, format_obs)
worksheet3.write(34,4, ExpenseAllocatePercentage[3], format_obs)
worksheet3.write(34,5, RiskSur_ins_exp_varexp_tel_tacadjust, format_obs)
worksheet3.write(34,6, RiskSur_ins_exp_varexp_tel_final, format_obs)
worksheet3.write(34,7, RiskSur_ins_exp_tel_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(34,8, RiskSur_ins_exp_varexp_tel_final * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

worksheet3.write(35,0, "费用风险-续期", format_rowlabel)
worksheet3.write(35,1, RiskSur_ins_exp_renew_decompose, format_obs)
worksheet3.write(35,2, RiskSur_ins_exp_varexp_renew_bench, format_obs)
worksheet3.write(35,3, RiskSur_ins_exp_varexp_renew_benchadjusted, format_obs)
worksheet3.write(35,4, ExpenseAllocatePercentage[4], format_obs)
worksheet3.write(35,5, RiskSur_ins_exp_varexp_renew_tacadjust, format_obs)
worksheet3.write(35,6, RiskSur_ins_exp_varexp_renew_final, format_obs)
worksheet3.write(35,7, RiskSur_ins_exp_renew_decompose * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)
worksheet3.write(35,8, RiskSur_ins_exp_varexp_renew_final * (Ratio_RisDiv_ins*Ratio_RisDiv_insmarcr) / RiskSur_total_aftbuffer, format_obs)

# sheet4 限额计算
worksheet4 = workbook.add_worksheet('限额')

worksheet4.set_column('A:A', 30)
worksheet4.set_column('B:B', 30)
worksheet4.set_column('C:C', 30)

worksheet4.write('A1', "指标", format_header)
worksheet4.write('B1', "限额", format_header)
worksheet4.write('C1', "实际值", format_header)

worksheet4.write(1, 0, "资产负债久期缺口-偿二口径", format_rowlabel)
worksheet4.write(1, 1, KRI_mar_int_DurGap_limit, format_obs)
worksheet4.write(1, 2, KRI_mar_int_DurGap, format_obs)

worksheet4.write(2, 0, "利率敏感资产占比", format_rowlabel)
worksheet4.write(2, 1, KRI_ASPercentage_InterSenAsset_limit, format_obs)
worksheet4.write(2, 2, KRI_ASPercentage_InterSenAsset, format_obs)

worksheet4.write(3, 0, "境内权益资产最低资本配置比例", format_rowlabel)
worksheet4.write(3, 1, KRI_MCpercent_equ_limit, format_obs)
worksheet4.write(3, 2, KRI_MCpercent_equ, format_obs)

worksheet4.write(4, 0, "上市权益资产VAR占比-99CL", format_rowlabel)
worksheet4.write(4, 1, KRI_VAR_ListedEquity_99CLVARratio_limit, format_obs)
worksheet4.write(4, 2, "暂无", format_obs)

worksheet4.write(5, 0, "上市权益资产配置比例", format_rowlabel)
worksheet4.write(5, 1, KRI_ASPercentage_ListedEquity_limit, format_obs)
worksheet4.write(5, 2, KRI_ASPercentage_ListedEquity, format_obs)

worksheet4.write(6, 0, "上市权益资产最低资本占用比", format_rowlabel)
worksheet4.write(6, 1, KRI_MCRatio_ListedEquity_limit, format_obs)
worksheet4.write(6, 2, KRI_MCRatio_ListedEquity, format_obs)

worksheet4.write(7, 0, "另类权益资产配置比例-总体", format_rowlabel)
worksheet4.write(7, 1, KRI_ASPercentage_AlterEquity_limit, format_obs)
worksheet4.write(7, 2, KRI_ASPercentage_AlterEquity, format_obs)

worksheet4.write(8, 0, "另类权益资产配置比例-房地产类", format_rowlabel)
worksheet4.write(8, 1, KRI_ASPercentage_AlterEquity_est_limit, format_obs)
worksheet4.write(8, 2, KRI_ASPercentage_AlterEquity_est, format_obs)

worksheet4.write(9, 0, "另类权益资产配置比例-能源类", format_rowlabel)
worksheet4.write(9, 1, KRI_ASPercentage_AlterEquity_energy_limit, format_obs)
worksheet4.write(9, 2, KRI_ASPercentage_AlterEquity_energy, format_obs)

worksheet4.write(10, 0, "另类权益资产配置比例-金融类", format_rowlabel)
worksheet4.write(10, 1, KRI_ASPercentage_AlterEquity_finance_limit, format_obs)
worksheet4.write(10, 2, KRI_ASPercentage_AlterEquity_finance, format_obs)

worksheet4.write(11, 0, "另类权益资产配置比例-其他类", format_rowlabel)
worksheet4.write(11, 1, KRI_ASPercentage_AlterEquity_oth_limit, format_obs)
worksheet4.write(11, 2, KRI_ASPercentage_AlterEquity_oth, format_obs)

worksheet4.write(12, 0, "另类权益资产最低资本占用比", format_rowlabel)
worksheet4.write(12, 1, KRI_MCRatio_AlterEquity_limit, format_obs)
worksheet4.write(12, 2, KRI_MCRatio_AlterEquity, format_obs)

worksheet4.write(13, 0, "投资性房地产资产配置比例", format_rowlabel)
worksheet4.write(13, 1, KRI_ASPercentage_RealEstate_limit, format_obs)
worksheet4.write(13, 2, KRI_ASPercentage_RealEstate, format_obs)

worksheet4.write(14, 0, "投资性房地产资产最低资本占用比", format_rowlabel)
worksheet4.write(14, 1, KRI_MCRatio_RealEstate_limit, format_obs)
worksheet4.write(14, 2, KRI_MCRatio_RealEstate, format_obs)

worksheet4.write(15, 0, "汇率风险价值占比-99CL", format_rowlabel)
worksheet4.write(15, 1, KRI_VAR_Exch_99CLVARratio_limit, format_obs)
worksheet4.write(15, 2, "暂无", format_obs)

worksheet4.write(16, 0, "交易对手违约风险最低资本占用比", format_rowlabel)
worksheet4.write(16, 1, KRI_MCRatio_def_limit, format_obs)
worksheet4.write(16, 2, KRI_MCRatio_def, format_obs)

worksheet4.write(17, 0, "固定收益类投资最低资本配置比例", format_rowlabel)
worksheet4.write(17, 1, KRI_MCpercent_fixin_limit, format_obs)
worksheet4.write(17, 2, KRI_MCpercent_fixin, format_obs)

worksheet4.write(18, 0, "另类固收资产配置比例", format_rowlabel)
worksheet4.write(18, 1, KRI_ASPercentage_alterfixin_limit, format_obs)
worksheet4.write(18, 2, KRI_ASPercentage_alterfixin, format_obs)

worksheet4.write(19, 0, "评级在AA级及以下公司债券占比", format_rowlabel)
worksheet4.write(19, 1, KRI_ASPercentage_corpbondbelowAA_limit, format_obs)
worksheet4.write(19, 2, "暂无", format_obs)

worksheet4.write(20, 0, "评级在AA级及以下另类固收资产占比", format_rowlabel)
worksheet4.write(20, 1, KRI_ASPercentage_alterfixinbelowAA_limit, format_obs)
worksheet4.write(20, 2, "暂无", format_obs)

worksheet4.write(21, 0, "13个月继续率-个险期交", format_rowlabel)
worksheet4.write(21, 1, KRI_ins_lap_ind_13RetenRate_limit, format_obs)
worksheet4.write(21, 2, KRI_ins_lap_ind_13RetenRate, format_obs)

worksheet4.write(22, 0, "13个月继续率-经代期交", format_rowlabel)
worksheet4.write(22, 1, KRI_ins_lap_bank_13RetenRate_limit, format_obs)
worksheet4.write(22, 2, KRI_ins_lap_bank_13RetenRate, format_obs)

worksheet4.write(23, 0, "13个月继续率-银保期交", format_rowlabel)
worksheet4.write(23, 1, KRI_ins_lap_agent_13RetenRate_limit, format_obs)
worksheet4.write(23, 2, KRI_ins_lap_agent_13RetenRate, format_obs)

worksheet4.write(24, 0, "25个月继续率-个险期交", format_rowlabel)
worksheet4.write(24, 1, KRI_ins_lap_ind_25RetenRate_limit, format_obs)
worksheet4.write(24, 2, KRI_ins_lap_ind_25RetenRate, format_obs)

worksheet4.write(25, 0, "25个月继续率-经代期交", format_rowlabel)
worksheet4.write(25, 1, KRI_ins_lap_bank_25RetenRate_limit, format_obs)
worksheet4.write(25, 2, KRI_ins_lap_bank_25RetenRate, format_obs)

worksheet4.write(26, 0, "25个月继续率-银保期交", format_rowlabel)
worksheet4.write(26, 1, KRI_ins_lap_agent_25RetenRate_limit, format_obs)
worksheet4.write(26, 2, KRI_ins_lap_agent_25RetenRate, format_obs)

worksheet4.write(27, 0, "死亡率偏差率", format_rowlabel)
worksheet4.write(27, 1, KRI_ins_los_dea_DevRate_limit, format_obs)
worksheet4.write(27, 2, "暂无", format_obs)

worksheet4.write(28, 0, "重疾发生率偏差率", format_rowlabel)
worksheet4.write(28, 1, KRI_ins_los_des_DevRate_limit, format_obs)
worksheet4.write(28, 2, "暂无", format_obs)

worksheet4.write(29, 0, "预算变动费用超支率-总体", format_rowlabel)
worksheet4.write(29, 1, KRI_overexp_budg_total_limit, format_obs)
worksheet4.write(29, 2, "暂无", format_obs)

worksheet4.write(30, 0, "预算变动费用超支率-个险与经代", format_rowlabel)
worksheet4.write(30, 1, KRI_overexp_budg_indi_agent_limit, format_obs)
worksheet4.write(30, 2, "暂无", format_obs)

worksheet4.write(31, 0, "预算变动费用超支率-银保", format_rowlabel)
worksheet4.write(31, 1, KRI_overexp_budg_bank_limit, format_obs)
worksheet4.write(31, 2, "暂无", format_obs)

worksheet4.write(32, 0, "预算变动费用超支率-网销", format_rowlabel)
worksheet4.write(32, 1, KRI_overexp_budg_web_limit, format_obs)
worksheet4.write(32, 2, "暂无", format_obs)

worksheet4.write(33, 0, "预算变动费用超支率-电销", format_rowlabel)
worksheet4.write(33, 1, KRI_overexp_budg_tel_limit, format_obs)
worksheet4.write(33, 2, "暂无", format_obs)

worksheet4.write(34, 0, "预算变动费用超支率-续期", format_rowlabel)
worksheet4.write(34, 1, KRI_overexp_budg_renew_limit, format_obs)
worksheet4.write(34, 2, "暂无", format_obs)

worksheet4.write(35, 0, "精算可用费用超支率-总体", format_rowlabel)
worksheet4.write(35, 1, KRI_overexp_actu_total_limit, format_obs)
worksheet4.write(35, 2, "暂无", format_obs)

worksheet4.write(36, 0, "精算可用费用超支率-个险与经代", format_rowlabel)
worksheet4.write(36, 1, KRI_overexp_actu_indi_agent_limit, format_obs)
worksheet4.write(36, 2, "暂无", format_obs)

worksheet4.write(37, 0, "精算可用费用超支率-银保", format_rowlabel)
worksheet4.write(37, 1, KRI_overexp_actu_bank_limit, format_obs)
worksheet4.write(37, 2, "暂无", format_obs)

worksheet4.write(38, 0, "精算可用费用超支率-网销", format_rowlabel)
worksheet4.write(38, 1, KRI_overexp_actu_web_limit, format_obs)
worksheet4.write(38, 2, "暂无", format_obs)

worksheet4.write(39, 0, "精算可用费用超支率-电销", format_rowlabel)
worksheet4.write(39, 1, KRI_overexp_actu_tel_limit, format_obs)
worksheet4.write(39, 2, "暂无", format_obs)

worksheet4.write(40, 0, "新增权益类不良资产金额", format_rowlabel)
worksheet4.write(40, 1, KRI_new_equ_NPA_limit, format_obs)
worksheet4.write(40, 2, "暂无", format_obs)

worksheet4.write(41, 0, "新增固定收益类不良资产金额", format_rowlabel)
worksheet4.write(41, 1, KRI_new_fixin_NPA_limit, format_obs)
worksheet4.write(41, 2, "暂无", format_obs)

worksheet4.write(42, 0, "权益类资产占比", format_rowlabel)
worksheet4.write(42, 1, KRI_ASPercentage_Equity_limit, format_obs)
worksheet4.write(42, 2, KRI_ASPercentage_Equity, format_obs)

worksheet4.write(43, 0, "境外投资资产占比", format_rowlabel)
worksheet4.write(43, 1, KRI_ASPercentage_Oversea_limit, format_obs)
worksheet4.write(43, 2, KRI_ASPercentage_Oversea, format_obs)

worksheet4.write(44, 0, "团险业务综合成本率", format_rowlabel)
worksheet4.write(44, 1, KRI_CCR_company_limit, format_obs)
worksheet4.write(44, 2, KRI_CCR_company, format_obs)



workbook.close()
